[package]
name = "wordbot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
poise = "0.6.1"
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "tls-native-tls", "sqlite", "migrate" ] }
tokio = { version = "1.47.1", features = ["full"] }
